### PR TITLE
Send analytics integration options to drift identify

### PR DESCRIPTION
**Pull request by mjelicic**
sends options object from `analytics.identify([userId], [traits], [options], [callback]);` to drift.identify as a third argument.

### CODE REVIEW

**Comment by mjelicic** [comment]
@Peripheral1994 @brennan @f2prateek can one of you guys please look at this?

**Comment by f2prateek** [comment]
Thanks for submitting this PR to update functionality. Currently we don’t have a timeline on when we might be able to merge in this change. We appreciate your patience, and please know that we’re working on processes to make it easier for partners to maintain destinations.

cc @srthurman

**Comment by mjelicic** [comment]
@f2prateek this is pretty important change for us and our users. We would like for it to go out asap. Can you please give me at least some rough estimate on when this can go out?

**Comment by srthurman** [comment]
Hi @mjelicic - I'm Sara, the Engineering Product Manager for our Destinations. I wish I had something more definitive I could share, but right now we really don't have an estimate for merging this change. We'll be sure to update here as there's any progress to share!

**Comment by mjelicic** [comment]
Hi @srthurman @f2prateek any updates on this? Do you guys have a better idea now when this could be merged?

**Comment by srthurman** [comment]
Thanks for checking in @mjelicic but no, there is no update on when this may be merged. Thanks for your patience here.

**Comment by mjelicic** [comment]
@srthurman any updates on this? is there any alternative?

**Comment by mjelicic** [comment]
Hi @srthurman any updates? Are you guys working on any alternatives that we can leverage?

**Comment by robbiet480** [comment]
@srthurman @f2prateek Any updates on this? Drift support just told us that they are dropping support for Segment. Can you provide any further information?

**Comment by mikeyparent** [comment]
@srthurman @f2prateek is there an update on when this will be merged?

**Comment by srthurman** [comment]
Hiya folks - I no longer work at Segment so I don't have any insight on if this will be merged into the `main` branch.

**Comment by robbiet480** [comment]
Thanks for the update @srthurman.

As for the others, our company left Drift because of this broken integration. They confirmed that they were no longer supporting Segment so don't expect this to be merged ever.

**Comment by mericsson** [comment]
Hi all -- this is queued for release expected Jan 4 week. I will update here when release is complete.

**Comment by mericsson** [comment]
Slight delay -- this is released to free & self service customers currently. All other customers should receive it Monday Jan 11.

**Comment by mericsson** [comment]
This is now fully deployed. Thank you!

**Pull request merged**
